### PR TITLE
Search packages from the build context

### LINKED ISSUE #1: Symbols not found inside godep GOPATH
(Moved from https://github.com/Microsoft/vscode-go/issues/250, I didn't realize the symbol lookup was a separate project)

I have a project using godeps to nest vendored packages.

The project root is at `/Users/myuser/go/src/github.com/myuser/myrepo`

The `"go.gopath"` setting is set to `"/Users/myuser/go/src/github.com/myuser/myrepo/Godeps/_workspace:/Users/myuser/go"`

Most things work (definition finding, etc), but "Show all symbols" does not include things inside the nested Godeps path (which is `Godeps/_workspace` relative to the project folder)

### PR DESCRIPTION
**Pull request by ironcladlou**
Search packages using the build Context. This finds symbols correctly
accounting for GOPATH and GOROOT, whereas the previous method was
incapable of searching all GOPATH elements (making search of vendored
code impossible).

Ignore the dir argument. It may be possible to use buildutil.FakeContext
to support the previous behavior which would facilitate symbol search
outside a GOPATH (e.g. a loose file tree), but that seems like a very
atypical use case. I suspect the most common use case is "I want to find
a symbol in GOPATH".

Fixes https://github.com/newhook/go-symbols/issues/1

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @lukehoban I've been trying to get @newhook's attention on this for a month now, hope he's doing okay.

**Comment by lukehoban** [comment]
It would be great to have this merged so that VS Code users who are working with vendored dependencies can get the benefits of Symbol Search.

**Comment by newhook** [comment]
Sorry, I'm on vacation I'll look in a week when I get back.

**Comment by ironcladlou** [comment]
Sounds like you're doing more than okay! Have a great time.

**Comment by dmitshur** [comment]
Friendly ping @newhook.

**Pull request closed without merging**
